return PlaceObj('ModDef', {
	'title', "Insects Level up All Species",
	'description', 'Credits go to https://steamcommunity.com/id/ivangr Mnementh who created the original implementation of the mod below.\nhttps://steamcommunity.com/sharedfiles/filedetails/?id=3010501248&searchtext=level+up\n\n[h1]Tired of fighting 200-250 stupidly weak units in each attack wave?[/h1]\nTired of crafting and using only the aoe weapons/defenses?\nWant the ability for the game to roll "titan" enemies that can solo bases? [i]WiP[/i]\n\nYou came to the right place!\n\n[h2][b]This mod force checks what the final # of enemies would be.[/b][/h2]\nA mod option # sets the max spawns in a single attack.\nA 160 Skarabei attack becomes an 80 Poisonous Skarabei attack.\nThis mod will re-check and re-upgrade until an animal grouping is being sent that\'s under your game option limit.\n\nSpecial notes:\n- Skarabei attacks will never switch to another base species\n- Skarabei are still individually weaker than Junos\n\nThe game option is respected [b]until[/b] maximum evolution is achieved\nIf a Skarabei attack is upgraded to "level 5 Poisonous Explosive Nanite-Injected Skarabei Brute" and the game [i]STILL[/i] thinks that 400 of them should be thrown at the player.... well then this mod starts popping popcorn, and rip to your base. ¯\\_(:D)_/¯\n\n[h1]Each tier is exponentially more difficult to deal with!/[/h1]\n[h2]Final Forms are base killers! They are not fair! [/h2]\n\nEach upgrade should feel close to the jump in difficulty from fightning a Shrieker Hatchling to a Shrieker Broodmother\n\n[h3]By default EVERY upgrade grants 2x health & 2x pain tolerance.[/h3]\nTHEN species specific upgrade(s) get applied.\nAka Skarabei will gain +10% pierce armour(As they are evolving to be highly resistant to arrows/bullets)\nHave fun discovering how each species is evolving to better defeat you!\n\n[h3]There are now at least 5 variants of all base animals, to enable significant upgrade paths.[/h3]\nSome special handling was taken for base game animal variants (Like Skarabei Brutes).\nAs new enemy tiers are found, they will require re-observing.\nThis gives you more vignettes into your colony.... but maybe more importantly and it will give you more details about strengths and weaknesses!\n\n[h3]Example[/h3]\nThis Mod\'s Final Form of the Skarabei Species is equivilant to 40 "regular" Skarabei\'s.\nThis means a mod option of 100 is respected until the base game calculations "would have sent" 4001 normal Skarabei to attack you!\n[b]Then and only then will there be 101+ FF Skarabei to attack you, not a single "Regular" Skarabei in sight.[/b]\n\n[h2]Insect Damage Overhaul![/h2]\nThe base Stranded Alien Dawn only gave animals piercing/blunt damage.\nNo longer!\nEach animal when observed, clearly states what damage they deal.\n- Scissorhands deal pure Piercing\n- Juno deal pure Blunt\n- Glutch deal pure Gas\n- Dragonly deal pure Energy\n- Tecatli\'s deal Energy/Gas\n- Skarabei now deal Blunt/Gas damage\n- Shriekers now deal Blunt/Pierce\n- Dogs deal Piercing/Energy\n\n[h2]Armor Rework![/h2]\nBase game armor only gave Blunt/Pierce resistances.\nNow each armor gives varying defensive benefits. (And some tools give defenses now)\n[b]Leather[/b] has great Energy resistance \n[b]Veggie Leather[/b] generally improves from base Leather\n[b]Synethic[/b] has great Pierce resistance\n[b]Carbon[/b] has great Blunt resistance\n[b]Improved Carbon[/b] is generally good, but not better than a full set of Synethic/Veggie/Base Carbon\n\n[h3]Tool Changes:[/h3]\n- EMUmbrella gives minor defensive buffs\n- Respirator Masks now give a large Gas defense\n- Good Luck Charms give minor defensive buffs\n\n[h3]Tame the same beasts! Benefit from their increased growth[/h3]\nAll species that can be tamed are still tame-able in their higher tier form!\nBUT each upgrade gives the creatures pacification defense, but also makes a successful tame after pacification less likely.\n\nSo how do you get one of these mega-beasts?\nWell be VERY careful when dealing with attacks....\nOR you can tame and befriend a lower tier mating pair.\nNow every new generation will be the next tiers genus!\nAll tame-able species (Juno, Shrieker, Scissorhands, Tecatli, & Dogs) also:\n- Eat less food per day (Final Forms eat the same as base game counterparts)\n- Have at least a 9x increased chance to become pregnant (And grow that much faster from a child)\n- Immediately Draftable (Although more training is recommended)\n- Tecatli & Dogs are inherently more difficult to train/breed\n\nWhen the game attacks you, it does not consider how many tames you have.\nSo a colony with no tames and 50 Final Form Shriekers get given the same attack strength!\n\nSo to summarize:\n- Tames are cheaper and quicker to deploy!\n- "Free" defense\n- Flamethrowers and AoE effects are not as useful and easy of a decision.\n\nAll this is meant to make it a tougher decision to avoid taming and using a large army of beasts to help your fledgling colony!',
	'image', "Mod/rtw6tLg/Images/New Creatures (1).png",
	'last_changes', '3.0 Originally meant as a "Clean up, Clean up, Everybody Everywhere!" small patch....\nBut here we are, with some major changes\n\n#1 Bugfix: Cleaned up mistype in an overridden base game attack.\n(Caused the base game single attack events to not spawn mobs) \n\n#2 Bugfix: Removed remnants of PX\n(Organs, Health Conditions, etc...)\n\n#3 Bugfix: Cleaned up mod Lua upgrade code\n(Caused infinite loops if all species in an attack where fully upgraded)\n\n#3 Buff (To players): Deathfly Nerfs:\n- no longer knocks back\n- crit chance nerfed to be negligible amount\n(meaning less likely to inflict bleeds)\n\n#4 Backwards Incompatible Change: Baby Raptors have officially been removed from mod; they are near useless as both a tame and enemy\n\n#5 Major Change: Junos, Shriekers, Scissorhands, Tecatli, & Dogs are now:\n- Lower chance to tame at higher tiers\n(This is in addition to a prior buff to their pacification resistance)\n- MUCH higher chance to tame at lower tiers \n(Due to lower tier allied tames getting outscaled rapidly)\n- MUCH faster to reproduce & grow \n(Halved base pregnancy time, base pregnancy chance x9)\n(final form pregnancy & growth time is now 48 hours)\n- MUCH less food eaten daily (Final Forms take base game amount of food)\n- Are immediately draft-able (After taming / birth their combat is lvl 5)\n- When they reproduce, their child is a tier higher\n(This lets you possibly achieve final form allied insects before you are attacked by them)\n-- Note 1 Tecatli are slower to breed/evolve.\n-- Note 2 Dogs are especially difficult to bring back to humanities side\n-- Note 3 Shriekers at higher tiers no longer have a male/female variant\n\n<color TextEmphasis>Dev note clarifying why these changes exist:</color>\nWith these changes (And other things in this mod)\n - Flamethrowers and AoEs are weaker with this mod\n(Due to reduced wave size, and insect resistances)\n- Tames are now "cheaper" by being faster to make\n- Tames need to eat less food making them cheaper resource wise.\n- Are <color TextEmphasis>NOT</color> used to calculate colony strength.\n(Meaning attacks will not be any stronger because you have 50 tamed Final Form Shriekers)\n\nAll of this combined changes the incentive structure and cost/benefit of capturing & training tames for defense.',
	'show_whats_new', "only once",
	'SpellCheck', true,
	'id', "rtw6tLg",
	'author', "Ark Builder",
	'version_major', 3,
	'version', 48,
	'lua_revision', 233360,
	'saved_with_revision', 352677,
	'code', {
		"Code/upgradeCall.lua",
		"UnitAnimal/Juno.lua",
		"UnitAnimal/Juno_Brute.lua",
		"UnitAnimal/Angry_Juno.lua",
		"UnitAnimal/Hulk_Juno.lua",
		"UnitAnimal/Too_Angry_Too_Die_Juno.lua",
		"UnitAnimal/Junoskar.lua",
		"UnitAnimal/Shrieker_Manhunting.lua",
		"UnitAnimal/Shrieker_Manhunting_Mother.lua",
		"UnitAnimal/Entropic_Shrieker.lua",
		"UnitAnimal/Plague_Sniper_Shrieker.lua",
		"UnitAnimal/Sniping_Entropy_Shielded_Shrieker.lua",
		"UnitAnimal/Scissorhands.lua",
		"UnitAnimal/Scissorhands_Brute.lua",
		"UnitAnimal/Brutal_Duelist_Scissorhands.lua",
		"UnitAnimal/Rage_Fueled_Scissorhand_Duelist.lua",
		"UnitAnimal/Rage_Focused_Scissorhands.lua",
		"UnitAnimal/VenomousRaptors.lua",
		"UnitAnimal/Tecatli.lua",
		"UnitAnimal/Entombed_Tecatli.lua",
		"UnitAnimal/Heat_Reinforced_Tecatli.lua",
		"UnitAnimal/Intelligent_Tecatli.lua",
		"UnitAnimal/Spellsword_Tecatli.lua",
		"UnitAnimal/Frenzied_Dragonfly.lua",
		"UnitAnimal/Frenzied_Bomber_Dragonfly.lua",
		"UnitAnimal/Frenzied_Fortified_Bomber_Dragonfly.lua",
		"UnitAnimal/Glutch_Stitcher.lua",
		"UnitAnimal/Bloated_Glutch.lua",
		"UnitAnimal/BadTrip_Bloated_Glutch.lua",
		"UnitAnimal/BadTrip_Bloated_Glutch_Stitcher.lua",
		"UnitAnimal/PEx_Skarabei.lua",
		"UnitAnimal/PEx_Skarabei_Brute.lua",
		"UnitAnimal/Mutated_PEx_Skarabei_Brute.lua",
		"UnitAnimal/Heavily_Mutated_PEx_Skarabei_Brute.lua",
		"UnitAnimal/dog_T1.lua",
		"UnitAnimal/dog_T3.lua",
		"UnitAnimal/dog_T4.lua",
		"UnitAnimal/dog_T5.lua",
		"Building/Turret_ToxicGun.lua",
		"UnitAnimal/Fast_Frenzied_Fortified_Bomber_Dragonfly.lua",
		"Robot/ILU_robot_monk_1.lua",
		"Robot/ILU_robot_assault_1.lua",
		"Robot/ILU_robot_sniper_1.lua",
		"Robot/ILU_robot_walker_fort_1.lua",
	},
	'has_options', true,
	'has_data', true,
	'saved', 1733141143,
	'code_hash', -213844251163107061,
	'screenshot1', "Mod/rtw6tLg/Images/Gltuch.PNG",
	'screenshot2', "Mod/rtw6tLg/Images/Scissorhands.PNG",
	'screenshot3', "Mod/rtw6tLg/Images/Juno.PNG",
	'screenshot4', "Mod/rtw6tLg/Images/Shrieker.PNG",
	'steam_id', "3350915173",
	'TagAnimals', true,
	'TagGameplay', true,
})